apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-go-serviceacc
  namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: client-go-role
rules:
- apiGroups: [""]
  resources:
    - pods
  verbs:
    - list
    - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: client-go-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: client-go-role
subjects:
- kind: ServiceAccount
  name: client-go-serviceacc
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-go-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: client-go-app
  template:
    metadata:
      labels:
        app: client-go-app
    spec:
      serviceAccountName: client-go-serviceacc
      containers:
      - name: client-go-app-container
        image: priyankass99/client-go-app:latest
        ports:
        - containerPort: 80
    
